//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriversOnRoutes
    {
        public int IdDriver { get; set; }
        public int IdOrder { get; set; }
        public Nullable<float> Award { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Order Order { get; set; }
    }
}
