//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.DriversOnRoutes = new HashSet<DriversOnRoutes>();
        }
    
        public int Id { get; set; }
        public int IdRoute { get; set; }
        public int IdClient { get; set; }
        public System.DateTime DateOfShipment { get; set; }
        public Nullable<System.DateTime> DateOfArrive { get; set; }
        public Nullable<byte> DeliveryStatus { get; set; }
        public Nullable<byte> PaymentStatus { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriversOnRoutes> DriversOnRoutes { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
